# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Dir-Recursive
version:      0.02
version_from: lib/IO/Dir/Recursive.pm
installdirs:  site
requires:
    IO::All:                       0
    IO::Dir:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
